### PR TITLE
Wait for the completion of deleting namespace in sc uninstall command

### LINKED ISSUE #28: failed install followed by uninstall doesn't unblock installation
My installation failed because I had not granted cluster admin access to myself. Running install again caused this failure:

```
$ sc install
generated service catalog deployment config in dir: /tmp/service-catalog021394536 
Service Catalog could not be installed
error deploying YAML files: deploy failed with output: exit status 1 :Error from server (AlreadyExists): error when creating "/tmp/service-catalog021394536/namespace.yaml": namespaces "service-catalog" already exists
```

I tried `sc uninstall` but it didn't clean up the namespace. It would be great to either have

1. Uninstall clean up the namespace, or,
2. Install re-use the namespace if it exists.

### LINKED ISSUE #114: `sc uninstall` should not print out the success message until the namespace is actually removed
I ran `sc install` right after getting the message "uninstalled service catalog successfully", and got the namespace AlreadyExists error:

> maqiuyu-macbookpro:installer maqiuyu$ ./output/bin/sc uninstall
> uninstalled service catalog successfully
> maqiuyu-macbookpro:installer maqiuyu$ ./output/bin/sc install
> generated service catalog deployment config in dir: /tmp/service-catalog625681308 
> Service Catalog could not be installed
> Error: error deploying YAML files: deploy failed with output: exit status 1 :Error from server (AlreadyExists): error when creating "/tmp/service-catalog625681308/namespace.yaml": object is being deleted: namespaces "service-catalog" already exists

Seems that the deletion of "service-catalog" namespace takes a couple more seconds to finish after command completes.

We should make sure the namespace is actually gone before printing out the success message.

### PR DESCRIPTION
**Pull request by maqiuyujoyce**
Fixes #114 
Fixes #28

### CODE REVIEW

File: installer/pkg/cmd/service_catalog.go [hunk 1]
```diff
@@ -450,15 +451,46 @@ func uninstallServiceCatalog(ns string) error {
...
 }
 
+// waitOnNSDeletion keeps checking whether namespace "service-catalog" is deleted.
+func waitOnNSDeletion() {
+	baseDelay := 100 * time.Millisecond
+	maxDelay := 6 * time.Second
+	retries := 0
+	var err error
+
+	for err == nil {
```
Comment (martinmaly) [inline installer/pkg/cmd/service_catalog.go]: the condition probably not needed if we return straight out on err != nil below

Comment (maqiuyujoyce) [reply installer/pkg/cmd/service_catalog.go]: Done.
